server:
  port: 80

cn:
  family:
    server:
      httpClient:                             #http配置服务
        maxTotal: 200                         #最大连接数
        defaultMaxPerRoute: 100               #并发数(单个路由最大连接数)
        connectTimeout: 1000                  #创建连接的最长时间
        connectionRequestTimeout: 500         #从连接池中获取到连接的最长时间
        socketTimeout: 10000                  #数据传输的最长时间
        staleConnectionCheckEnabled: true     #提交请求前测试连接是否可用
  aliyun:
    regionId: 'cn-hangzhou'
    accessKey: 'LTAI5tNZeXWhCeMjXSy7mcCk'
    accessSecret: 'QnMEwDyDC7jkV06UDbtMRIB63jPEUk'
  config:
    url: 'https://jsonip.com'
    domainName: 'family-cloud.cn'



